### PR TITLE
feature: unable to use CRDs imported as modules

### PR DESCRIPTION
**Pull request by 9bany**
### Proposed changes
- issue link: https://github.com/nginxinc/kubernetes-ingress/issues/3770
- description: able to import module with `/v3` 

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Comment by jjngx** [comment]
@9bany could you please update the PR to fix the conflict and push changes?

**Comment by jjngx** [comment]
@9bany thank you for contributing! Great work! Could you please resolve conflict and push your changes? We would be happy to merge your PR.

**Review by jjngx — APPROVED** [review]
🚀 LGTM

**Review by jjngx — APPROVED** [review]

**Comment by jjngx** [comment]
@9bany could you please run `make lint` and `gofumpt` and push your updates? It seems like `internal/k8s/controller.go` needs to be formatted.

```bash
➜  kubernetes-ingress git:(9bany/main) make lint

// output partially omitted

internal/k8s/controller.go:27: File is not `gofmt`-ed with `-s` (gofmt)
  "github.com/nginxinc/kubernetes-ingress/v3/pkg/apis/dos/v1beta1"
	"golang.org/x/exp/maps"
INFO File cache stats: 1 entries of total size 143.7KiB
INFO Memory: 12 samples, avg is 43.7MB, max is 89.7MB
INFO Execution took 1.094010333s
make: *** [lint] Error 1
```

**Review by jjngx — APPROVED** [review]
👍🏻

**Comment by jjngx** [comment]
@9bany could you please update branch push your changes?

**Comment by jjngx** [comment]
@9bany could you please open (change this PR) a PR from your fork and the branch name different than `main`? So, fork the project, create a branch for your fix and open PR?
It could be sth like:
```bash
NGINX:main <- 9bany:module-support
```
where `module-support` is the name of your branch

**Comment by jjngx** [comment]
@9bany any update on this? Would you be able to send 2nd PR from your branch different than `main`?

**Comment by 9bany** [comment]
All done, please check my new pull request [here](https://github.com/nginxinc/kubernetes-ingress/pull/4152) @jjngx

**Comment by jjngx** [comment]
thanks @9bany , I will start working on your PR soon.

**Comment by 9bany** [comment]
@jjngx 
I haven't run it yet.
but
I tried to fix it, but nothing changed when I ran it.
Screenshot 2023-07-27 at 15 23 40

**Pull request closed without merging**
