### PR TITLE
[cherry-pick] docs: enableGitInfo config (#6577)

### PR DESCRIPTION
**Pull request by nginx-jack**
Cherry-pick enableGitInfo config and docs-action bump

This enables enableGitInfo config to fix incorrect last-modified docs values.

### CODE REVIEW

**Review by vepatel — APPROVED** [review]

**Review by AlexFenlon — APPROVED** [review]

**Comment by vepatel** [comment]
@nginx-jack looks like make-docs is failing

**Comment by nginx-jack** [comment]
> @nginx-jack looks like make-docs is failing
By default the checkout action clones at depth `1`, hugo now needs full history so it can add last modified dates as part of it's build. Can I update `ci.yml` to increase the clone depth?

**Comment by vepatel** [comment]
@nginx-jack sure, it the checkout is specific to this job the shouldn't be an issue. Probably need to get it in `main` first

**Comment by nginx-jack** [comment]
> @nginx-jack sure, if the checkout is specific to this job the shouldn't be an issue. Probably need to get it in `main` first

I'll need to make some more tweaks, since the action is using docker to build, it doesn't have the git context at all as it's only mounting the `site` directory, and no the root level folder. Will try get it sorted today!

**Comment by nginx-jack** [comment]
@vepatel PR here for a workaround https://github.com/nginxinc/kubernetes-ingress/pull/6597.
I'd like a better solution, that still provided git info for the hugo build, so I'll add an item in our backlog to address it.

**Comment by nginx-jack** [comment]
I'm going to close this for now. There's an outstanding docs PR that wasn't cherry-picked yet. https://github.com/nginxinc/kubernetes-ingress/pull/6554
I'll get that in first, and then queue up the rest of the changes.
Would you prefer I do them as multiple cherry pick MRs, or a single one?

**Pull request closed without merging**
