### PR TITLE
Bump docs-action to v1.0.5

### PR DESCRIPTION
**Pull request by nginx-jack**
### Proposed changes

Bump docs-action to v1.0.5.
Adds support for latest hugo and nginx hugo theme version.

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Review by j1m-ryan — APPROVED** [review]

**Comment by nginx-jack** [comment]
I have hereby read the F5 CLA and agree to its terms

**Review by ADubhlaoich — APPROVED** [review]
@nginx-jack If you could make a cherry pick to the release branch, it'd be appreciated!

**Review by Jcahilltorre — APPROVED** [review]

**Comment by ADubhlaoich** [comment]
I have hereby read the F5 CLA and agree to its terms

**Comment by ADubhlaoich** [comment]
recheck

**Pull request merged**
