### PR TITLE
Self-signed certs updates as old certs were expired

### PR DESCRIPTION
**Pull request by sdutta9**
### Proposed changes

As part of this PR, I am updating the old self-signed certs with new ones that are valid for 5 years. 

Related Bug: https://github.com/nginxinc/kubernetes-ingress/issues/6433

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [X] I have rebased my branch onto main
- [X] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Review by vepatel — APPROVED** [review]

**Review by j1m-ryan — APPROVED** [review]

**Review by jjngx — APPROVED** [review]

**Comment by danielnginx** [comment]
I have hereby read the F5 CLA and agree to its terms

**Comment by AlexFenlon** [comment]
Hi @sdutta9,

We appreciate your work on this but we are going to do a different approach.

We will give you credit for your contribution on our release notes once that becomes available in v4.0.0.

I hope you are happy about this.

**Comment by sdutta9** [comment]
> Hi @sdutta9,
> 
> We appreciate your work on this but we are going to do a different approach.
> 
> We will give you credit for your contribution on our release notes once that becomes available in v4.0.0.
> 
> I hope you are happy about this.
Hi @AlexFenlon 

I care the least about credits as long as the expired certificates are fixed. To me updating certificates is a simple task, and being part of F5 which is a security-first company, I don't feel comfortable sharing an example with expired certificates (even if they are self-signed and only used as a sample example) with customers. I will surely be happy the sooner you fix all expired certs in the main branch. 🙂

**Comment by pdabelf5** [comment]
Resolving as the issue has been addressed in PR https://github.com/nginxinc/kubernetes-ingress/pull/6714.  Thank you @sdutta9 for your work on this.

**Pull request closed without merging**
