### PR TITLE
Add rewrites annotation

### LINKED ISSUE #63: Introduce annotation for rewrite rule
See #60

Instead of hard-coding the rewrite rule one could introduce a further annotation like in #61.

### PR DESCRIPTION
**Pull request by jmastr**
Closes #63

### CODE REVIEW

**Comment by jmastr** [comment]
@pleshakov please review

**Comment by pleshakov** [comment]
@jmastr 
Thx for another pull request!

A few suggestions:

- Remove `{{if $location.Rewrite}}/{{end}}` from `location {{$location.Path}}{{if $location.Rewrite}}/{{end}}` in the `ingress.tmpl`.  I think it's better to stay transperent. I'll add notes about the necessity to put `/` at the end of Ingress paths it to the README file.

- Don't validate the service name and the URL in the annotation.
```go
r, _ := regexp.Compile("serviceName=([a-z\\-]+) +rewrite=([/a-z0-9]+)")
```
A service name can also contain numbers.  A URL can contain characters like `_`. I suggest to not perform validation at all. If a service name is not valid, the controller will simply igoner the service later. If a URL is not correct, NGINX will report error in the logs when the controller does the configuration check before reloading the configuration.

Please look at https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-plus-controller/nginx/configurator.go#L232 , where we're parsing a similar annotation.

- Add logging. Please add error reporting when the annotation doesn't include all the required parts, similar to https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-plus-controller/nginx/configurator.go#L232

- It might be helpful to write a unit test similar to this one https://github.com/nginxinc/kubernetes-ingress/blob/master/nginx-plus-controller/nginx/configurator_test.go

**Comment by jmastr** [comment]
Very nice! Will do!

**Comment by jmastr** [comment]
Hi @pleshakov,

I worked in your comments about parsing, logging and testing.

Note that I removed the `/` at the end of `location {{$location.Path}}` from my patch, but I added it to `examples/rewrites/README.md` already to be consistent.

**Comment by pleshakov** [comment]
@jmastr 
Awesome!

Could you replace `nginx.com` with `nginx.org`  in the  following line in `configurator.go` : `glog.Errorf("In %v nginx.com/rewrites contains invalid declaration: %v, ignoring", ingEx.Ingress.Name, err)`  ?

**Comment by jmastr** [comment]
@pleshakov done

**Comment by pleshakov** [comment]
Great. Thx

**Comment by pleshakov** [comment]
We'll prepare a new release -- https://github.com/nginxinc/kubernetes-ingress/releases --  that will have this and other features. A new tag will be published to the https://hub.docker.com/r/nginxdemos/nginx-ingress/ repo.

**Comment by jmastr** [comment]
That's awesome! Thank you very, very much!

**Comment by jmastr** [comment]
I am going to give a talk about this at the next Kubernetes meetup in Berlin, Germany.

**Comment by pleshakov** [comment]
That's awesome!!

**Pull request merged**
