### PR TITLE
Fixed hyperlinks.

### PR DESCRIPTION
**Pull request by pammecrandall**
### Proposed changes
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [ ] I have rebased my branch onto master
- [ ] I will ensure my PR is targeting the master branch and pulling from my branch from my own fork

### CODE REVIEW

**Review by pleshakov — COMMENTED** [review]
Hi @pammecrandall 

Looks good!

I also noticed a link problem in this table https://docs.nginx.com/nginx-ingress-controller/troubleshooting/troubleshooting-with-app-protect/  Could you fix it as well?

Also, there are two tables that are missing:
- this table got lost completely during  the migration -- https://github.com/nginxinc/kubernetes-ingress/blob/v1.12.0/docs-web/configuration/global-configuration/configmap-resource.md#modules .
- this table is missing as well -- https://github.com/nginxinc/kubernetes-ingress/blob/v1.12.0/docs-web/configuration/ingress-resources/advanced-configuration-with-annotations.md#app-protect

Would it make sense to bring back those tables in this PR or a separate PR?

Thanks

**Comment by pleshakov** [comment]
(I rebased the dev branch against the master to resolve the reported conflicts)

**Comment by pammecrandall** [comment]
@pleshakov Thank you for doing that.  I can add the missing table fix in this PR.  I set the base branch to development but should it be master?

**Comment by jputrino** [comment]
It's ok to do it either way - we use development for testing and staging mostly for a preview. I'm fine with merging fixes like this directly into master.

**Comment by pammecrandall** [comment]
@jputrino  Okay.  Cool.  I'll change the base branch to master.  

@pleshakov I added the missing table and another one that had been left out so this PR should be good now.  

I'm working on the links in  https://docs.nginx.com/nginx-ingress-controller/troubleshooting/troubleshooting-with-app-protect/ now and I'll check for missing tables there and nginx app protect docs too.  Thanks!

**Review by ciarams87 — APPROVED** [review]

**Review by pleshakov — APPROVED** [review]

**Pull request merged**
