### PR TITLE
Allow to specify image with digest in helm chart

### LINKED ISSUE #2978: Allow to specify image with digest in helm chart
**Is your feature request related to a problem? Please describe.**
I want to be able to specify image with digest (instead of tag) for the following reasons:

- Using OKD/OpenShift ImageContentsourcePolicy requires you to specify image by digest
- It is more secure and a recommended practice to specify image by digest

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by hafe**
Closes #2978

### Proposed changes
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [X] I have updated necessary documentation
- [X] I have rebased my branch onto main
- [X] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

Are there tests for the helm chart?

### CODE REVIEW

**Review by lucacome — APPROVED** [review]
Thanks again for the PR @hafe !

Would you mind adding the new parameter to our website docs here `docs/content/installation/installation-with-helm.md`?

**Comment by hafe** [comment]
> Thanks again for the PR @hafe !
> 
> Would you mind adding the new parameter to our website docs here `docs/content/installation/installation-with-helm.md`?

Done!

**Comment by hafe** [comment]
Did I do the right thing? I did rebase from main and force push.

**Comment by lucacome** [comment]
Yep @hafe I'm just waiting for a second review from the team before I merge it @nginxinc/kic

**Review by ciarams87 — APPROVED** [review]
LGTM, thanks!!

**Pull request merged**
