### PR TITLE
Support new directive for dos: app_protect_dos_arb_fqdn

### PR DESCRIPTION
**Pull request by pasmant**
### Proposed changes
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [ ] I have rebased my branch onto master
- [ ] I will ensure my PR is targeting the master branch and pulling from my branch from my own fork

### CODE REVIEW

**Comment by lucacome** [comment]
> For review, the merge need to be done after the new dos release will be publish

@pasmant when is the release scheduled for?

**Comment by pasmant** [comment]
> > For review, the merge need to be done after the new dos release will be publish
> 
> @pasmant when is the release scheduled for?

@lucacome, The release is scheduled to the second week of April.

**Comment by lucacome** [comment]
@pasmant would it make sense to close this and re-open it when the feature is ready instead of leaving this PR open for more than a month?

**Comment by pasmant** [comment]
> @pasmant would it make sense to close this and re-open it when the feature is ready instead of leaving this PR open for more than a month?

OK, I will close the PR and reopen it when dos will release

**Pull request closed without merging**
