### PR TITLE
Run pre-commit hooks to fix python test imports

### PR DESCRIPTION
**Pull request by lucacome**
- Removes unused imports in tests
- Adds `fixtures` and `utils` folders to move non-tests files from the main folder
- Re-orders dependencies in the requirements files alphabetically 
- Fixes whitespaces in a few remaining files

### CODE REVIEW

**Review by tomasohaodha — CHANGES_REQUESTED** [review]
Impossible to review a PR with 511 files changed with just 'Fixes all the formatting in the codebase' as the description. Either package it to have fewer files per review, or explain in-depth what is being changed so that anomalies can be easily detected.

**Comment by haywoodsh** [comment]
Hi @lucacome, should there also be corresponding checks in the CI pipeline for the hooks you added? From what I understand about pre-commit hooks, users can skip them if they choose to. If the same tests don't exist in the CI pipeline, could it be possible that a pull request is merged without passing those commit hooks, and the next developer who pull from the main branch will have have to fix the code themselves?

**Comment by lucacome** [comment]
@haywoodsh yes there's going to be a check. I've enabled it briefly but it was trying to fix all the files at once instead of fixing only the modified files. I haven't found a way yet to customize the app, so I've disabled it for now.
This PR is basically taking care of all the existing issues so that we can enable the check.

**Comment by lucacome** [comment]
@tomasohaodha I've opened #3223 to move some of the docs changes there

**Comment by tomasohaodha** [comment]
It's still showing all the whitespace-changed files. I assume you need to merge https://github.com/nginxinc/kubernetes-ingress/pull/3223 and then run the pre-commit again?

**Comment by lucacome** [comment]
@tomasohaodha yes just merged `main` into this branch and also created another PR to take care of whitespaces in tests #3226

**Review by ciarams87 — APPROVED** [review]

**Review by tomasohaodha — APPROVED** [review]

**Pull request merged**
