### PR TITLE
Update go.mod

### PR DESCRIPTION
**Pull request by LuoYuWuSheng**
solve go mod problem according to :

https://github.com/ecordell/contour/commit/fff01bd7c52a7b22c9d5c75c1682de36b11cdb8d

### Proposed changes
Describe the use case and detail of the change. If this PR addresses an issue on GitHub, make sure to include a link to that issue here in this description (not in the title of the PR).

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x]  I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Comment by ciarams87** [comment]
Hi @LuoYuWuSheng!

Thanks for your contribution 😃 

Could you please open an issue explaining the problem you are facing according to our [contributing guidelines](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md#contributing)?

Thank you!

**Comment by LuoYuWuSheng** [comment]
of course!   😃

**Comment by lucacome** [comment]
@LuoYuWuSheng I think this will be fixed after we merge https://github.com/nginxinc/kubernetes-ingress/pull/3924

**Comment by LuoYuWuSheng** [comment]
> 

got it

**Comment by lucacome** [comment]
This was fixed by #3924

**Pull request closed without merging**
