### PR TITLE
Sort helm chart lines ascending alphabetically

### PR DESCRIPTION
**Pull request by aknot242**
### Proposed changes
Addresses #2999 

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [X] I have updated necessary documentation
- [ ] I have rebased my branch onto main
- [ ] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Review by lucacome — CHANGES_REQUESTED** [review]
Hi @aknot242 thanks for the PR!

The docs are (mostly) aligned with the `values.yaml` so I think we would need to change the order there too if we want to change in the docs, and also in the `README.md`

**Comment by aknot242** [comment]
@lucacome I respectfully disagree. While the order in the helm chart would ideally match the docs, that is beyond the scope of the issue created. If someone wants to contribute it, that's fine but it would represent quite a bit of manual work to sort it and I'll let someone else contribute that (ideally the dev team, as IMO, seems like it was earned tech debt). 

I can meet you in the middle by sorting the README, but it seems strange that the values exist there separately from in the hugo docs - seems needlessly duplicative. I'll re-order the README in a commit here shortly.

**Comment by jasonwilliams14** [comment]
@aknot242 We took a good look at this and discussed internally. We came the conclusion that we are going to stay with the way things currently are. 
Thank you.

**Comment by aknot242** [comment]
Would be good to document the reasons behind the decision. Doing it in the linked issue (#2999) might be ideal. What is the sorting scheme that is currently in place? Thx.

**Pull request closed without merging**
