### PR TITLE
Condition jwt

### PR DESCRIPTION
**Pull request by outcast**
Adding validation for jwt variables for conditionals. this will also allow for other variables group (wildcard) to be added quickly.

### Proposed changes
Added wildcard logic to condition variable validation to allow for quick validation of variable groups. The primary use case is for jwt variables.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [ x ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/master/CONTRIBUTING.md) doc
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] I have checked that all unit tests pass after adding my changes
- [ x ] I have updated necessary documentation
- [ x ] I have rebased my branch onto master
- [ x ] I will ensure my PR is targeting the master branch and pulling from my branch from my own fork

* I have write test for the validator, I need some help with the tests for the config generator.

### CODE REVIEW

**Comment by outcast** [comment]
I did use the gofmt not sure why the lint is failing. Sorry still new to go.

**Comment by vepatel** [comment]
@outcast can you please run `gofumpt` on `virtualserver.go`.

**Comment by outcast** [comment]
> @outcast can you please run `gofumpt` on `virtualserver.go`.

done!

**Comment by outcast** [comment]
Ok running all linters manually this time.

**Comment by gallarda** [comment]
James is talking about using a "Match" for routing a request as documented here: https://docs.nginx.com/nginx-ingress-controller/configuration/virtualserver-and-virtualserverroute-resources/#match

For example, if `user=john` route to `coffee-future` and if `user=bob` route to `coffee-deprecated`

Today, we can access the key/value to be tested through a header, cookie, argument, or a variable.

Another way a key/value can be shared with nginx is through a JWT claim. Using a JWT has the advantage of a digital signature that prevents modification and unauthorized requests.

For example, a JWT claim named `user` is accessed by nginx through a variable named `$jwt_claim_user`. The key name in a JWT claim can be anything you want. All James did was add a JWT claim to the existing list of variables supported by a match condition.

So, if you take the example from the docs:

```
path: /coffee
matches:
- conditions:
  - cookie: user
    value: john
  action:
    pass: coffee-future
- conditions:
  - cookie: user
    value: bob
  action:
    pass: coffee-deprecated
action:
  pass: coffee-stable
```

It would look like this when using a JWT:

```
path: /coffee
matches:
- conditions:
  - variable: $jwt_claim_user
    value: john
  action:
    pass: coffee-future
- conditions:
  - variable: $jwt_claim_user
    value: bob
  action:
    pass: coffee-deprecated
action:
  pass: coffee-stable
```

**Comment by lucacome** [comment]
@outcast would you mind rebasing your PR and resolving conflicts?

**Comment by outcast** [comment]
@lucacome not sure what to do about the linting failing. However, I have completed the rebasing.

**Comment by lucacome** [comment]
@outcast I think something went wrong with the rebase, I see a lot of changes unrelated to yours 🤔

**Comment by jasonwilliams14** [comment]
We are going to review this internally. Closing.

**Pull request closed without merging**
