### PR TITLE
automate kindest/node versions

### PR DESCRIPTION
**Pull request by j1m-ryan**
### Proposed changes

https://github.com/nginxinc/kubernetes-ingress/issues/4771

Automate the `kindest/node` versions so the tests use the latest patches of the 7 latest minior versions from docker hub.

At the time of writing, the `latest_kindest_node_versions` variable becomes this `\"1.23.17\", \"1.24.15\", \"1.25.11\", \"1.26.6\", \"1.27.3\", \"1.28.0\", \"1.29.0\"`

I briefly switched a condtion to test what nightly would look like. Below is the tests that run upon changing switching scheduler condition. Which I have now switched back.

image

I cancelled the run as its the nightly suite, but it appeared to be running fine, and getting the correct versions.

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [ ] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Review by jjngx — APPROVED** [review]
👍🏻

**Comment by vepatel** [comment]
@jimf5 is it possible to run latest `main` and `PRs` on 1.29.0 now that its available and switching the logic from using tests/dockerfile to this one?

**Comment by j1m-ryan** [comment]
yeah i can change the logic for not scheduled commits, will do that now

**Comment by j1m-ryan** [comment]
@vepatel its getting the kindest latest version for non scheduled runs also now, and seems to have passed all of them on `1.29.0`

**Review by vepatel — APPROVED** [review]

**Pull request merged**
