### PR TITLE
Create use-cases.md

### PR DESCRIPTION
**Pull request by brianehlert**
Initial create of Use Case based directory

### Proposed changes
Add a Use Case based directory that describes use cases and links off to the pertinent documentation as well as related examples.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [x ] I have updated necessary documentation
- [x ] I have rebased my branch onto main
- [x ] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Review by jjngx — APPROVED** [review]

**Comment by lucacome** [comment]
@brianehlert it looks like something's wrong with the layout/formatting of the page https://deploy-preview-3872--nginx-kubernetes-ingress.netlify.app/nginx-ingress-controller/use-cases/

**Comment by brianehlert** [comment]
> @brianehlert it looks like something's wrong with the layout/formatting of the page https://deploy-preview-3872--nginx-kubernetes-ingress.netlify.app/nginx-ingress-controller/use-cases/

I have the formatting fixed in GitHub.  I found a number of embedded CR/LF that was killing the table.
Not positive on the better way to handle the Netlify preview for the table though.

**Comment by lucacome** [comment]
@nginxinc/nginx-docs maybe can help?

**Comment by ADubhlaoich** [comment]
The GitHub preview for this document isn't sufficient for determining its correctness.

I will start pushing changes to try and alleviate the readability but it's pushing the limits of what a table is intended for: I may have to restructure the entire page.

**Comment by travisamartin** [comment]
Consider replacing the table with section headings so the presentation is more user-friendly and nicer looking -- the ginormous table won't work on mobile. 

image

**Comment by ADubhlaoich** [comment]
There's some ideas in this PR I think we can pull into future documentation work, but it relates to IA and critical paths. Closing it since it's been lingering for a long time.

**Pull request closed without merging**
