### PR TITLE
Mo: add option to turn off stream logs when access log is set to off

### PR DESCRIPTION
**Pull request by Binsabbar**
### Proposed changes
During DoS attack the stream logs still writes logs, unlike when it is in HTTP, where the DoS automatically turn off access log based on the value of `$loggable` used in dos access log. 

Since there is already an option to turn off `access_log` for default http server, it was not added for default stream server. I used the same variable to also turn off the stream access log. 

If a new variable is preferred, please let me know.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [X] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have checked that all unit tests pass after adding my changes
- [X] I have updated necessary documentation
- [X] I have rebased my branch onto main
- [X] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Comment by haywoodsh** [comment]
Hi @Binsabbar Thanks for submitting this pull request. We're currently reviewing your proposed changes with the team to investigate the impact of this and determine if we need to use another config map key for the stream block. We'll let you know as soon as possible. Thanks for your patience.

**Review by lucacome — APPROVED** [review]
Seems reasonable to me. @Binsabbar can you please update your commit message and PR title following the [guidelines](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md#git-style-guide)? Thanks!

**Comment by Binsabbar** [comment]
> Seems reasonable to me. @Binsabbar can you please update your commit message and PR title following the [guidelines](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md#git-style-guide)? Thanks!

Sure I will work on that

**Comment by Binsabbar** [comment]
> Seems reasonable to me. @Binsabbar can you please update your commit message and PR title following the [guidelines](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md#git-style-guide)? Thanks!

Sure I will work on that

**Comment by Binsabbar** [comment]
@lucacome @haywoodsh I am having a second though about how I implemented this. Currently there are two variables to control `access_log` for `server` blocks in the`http` block. 

- `AccessLogOff` in template file, which controls overall non-default `server` blocks.
- `DefaultServerAccessLogOff` in template file, which only controls the default `server` block in `http` block.

In my PR I used `AccessLogOff` as a way to control stream block default logs. The `AccessLogOff` if set to true will also turn off the logs for `server` blocks in the `http` block.

I can think of two options:

1. Use `DefaultServerAccessLogOff` to also turn off `stream` logs.
2. Introduce new configuration key to control `stream` access logs name it `StreamAccessLogOff`.


what do you think? (I will need some directions on implementing option 2.

**Comment by Binsabbar** [comment]
HI @brianehlert , can you provide me with a preferred option? and in case of option 2, can you provide me with direction?

**Comment by shaun-nx** [comment]
Hi @Binsabbar apologies for the delay on our responding to this.
I would say having the `StreamAccessLogOff` option would be best. If you still want help in knowing what files you should edit for this please let us know.

Since this would be a new `ConfigMap` key, we will need to add an entry for that setting in our docs here: https://docs.nginx.com/nginx-ingress-controller/configuration/global-configuration/configmap-resource/#logging

There is currently a PR open which will be re-structuring our docs. I would wait for this PR to be merged before making any docs related changes (This PR is expected to be merged today 🤞 ) https://github.com/nginxinc/kubernetes-ingress/pull/4620

**Comment by j1m-ryan** [comment]
We recently merged a PR that changed logging behaviour. We interested in brining this functionality from http to stream. We have an issue for it here https://github.com/nginxinc/kubernetes-ingress/issues/6171. Are you still interested in doing this?

**Pull request closed without merging**
