### PR TITLE
add securityContext incontainer spec

### PR DESCRIPTION
**Pull request by davidstack**
when create nginx ingress controller, the nginx failed to start. after kubernetes 1.1,we need add securityContext in container spec.
`securityContext:
          privileged: true`

### CODE REVIEW

**Comment by pleshakov** [comment]
Hi, what error are you getting?  Why do you need to run NGINX container in a privileged mode?

**Comment by davidstack** [comment]
@pleshakov  In my k8s cluster,without this securityContext, the nginx controller cant not start.
can nginx controller start in you enviroment? my k8s version is 1.3

**Comment by pleshakov** [comment]
@davidstack  yes, it works in my environment.

Did you make any changes in the controller yaml files? What errors are you getting?

**Comment by davidstack** [comment]
@pleshakov ,my k8s version is :+1: 

> Client Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.0.227+63905492f02de6-dirty", GitCommit:"63905492f02de6f9f9165511bfef454546bc9bad", GitTreeState:"dirty", BuildDate:"2016-09-07T10:17:12Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5+", GitVersion:"v1.5.0-alpha.0.227+63905492f02de6-dirty", GitCommit:"63905492f02de6f9f9165511bfef454546bc9bad", GitTreeState:"dirty", BuildDate:"2016-09-07T10:17:12Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

my controller yaml is 

> apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx-ingress-controller
spec:
  template:
    metadata:
      labels:
        name: nginx-ingress-controller
    spec:
      # nodeSelector:
      #   role: nginx-ingress
      containers:
      - image: 10.110.17.138:5000/nginxdemos/nginx-ingress:0.3
        imagePullPolicy: Always
        name: nginx-ingress
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443

when i create this daemonset,the pod failed with this desc:

>   4s	4s	1	{kubelet master.iop.com}	spec.containers{nginx-ingress}	Normal	Created		Created container with docker id 52e89005b815; Security:[seccomp=unconfined]
  47s	3s	5	{kubelet master.iop.com}	spec.containers{nginx-ingress}	Warning	BackOff		Back-off restarting failed docker container
  3s	3s	1	{kubelet master.iop.com}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "nginx-ingress" with CrashLoopBackOff: "Back-off 40s restarting failed container=nginx-ingress pod=nginx-ingress-controller-on7v5_kube-system(549c8d09-9981-11e6-885d-005056810fa0)"

the pod logs is :+1: 
`F1024 00:45:37.670877       1 nginx.go:196] Failed to start nginx`

**Comment by pleshakov** [comment]
Thanks for providing the logs. If it's possible, could you uncomment lines 24-25 here https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/daemon-set/nginx-ingress.yaml . This way we can get more details on why NGINX isn't able to start

**Comment by peterkellyonline** [comment]
Closing PR as it is out of date, despite the great work done by the submitter! Let's see if we can add this to our backlog internally and work on something similar.

**Pull request closed without merging**
