### PR TITLE
Add isort and Black

### PR DESCRIPTION
**Pull request by lucacome**
- Adds isort and Black
- Formats all the tests

### CODE REVIEW

**Comment by lucacome** [comment]
@vepatel I noticed this warning 🤔 
```
.../tests/suite/test_prometheus_metrics.py:191: SyntaxWarning: assertion is always true, perhaps remove parentheses?
```

**Comment by vepatel** [comment]
@lucacome `.../tests/suite/test_prometheus_metrics.py:191: SyntaxWarning: assertion is always true, perhaps remove parentheses?` is a legitimate warning because interpreter is treating it as a tuple which is equivalent to assert True, removing parentheses will fix it.

**Comment by vepatel** [comment]
@lucacome seems like linter is failing to execute, should we include a`pyproject.toml` with black and flake8 config?

**Comment by lucacome** [comment]
the `pyproject.toml` already has black, but unfortunately flake8 doesn't support it at least for now https://github.com/PyCQA/flake8/issues/234#issuecomment-1206730688

did you run `make lint-python`? you would need to run it manually (the workflow in the CI is just a check)...at least until this goes in https://github.com/nginxinc/kubernetes-ingress/pull/2154 😅

**Review by vepatel — APPROVED** [review]

**Review by tomasohaodha — APPROVED** [review]

**Pull request merged**
