### PR TITLE
Fix dashboard 2940

### PR DESCRIPTION
**Pull request by hafe**
### Proposed changes

Maintenance of the existing Grafana dashboard. Query values for variables properly and use variables in expressoions where applicable.

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [X ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ X] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [ X] I have rebased my branch onto main
- [ X] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Comment by hafe** [comment]
Do I need to do something more to get this reviewed?

**Comment by jasonwilliams14** [comment]
> Do I need to do something more to get this reviewed?

Hey @hafe 
We just need to look on our side. I will plan to put this on my todo list this week.

**Comment by jasonwilliams14** [comment]
> Do I need to do something more to get this reviewed?

This looks good @hafe 
Thank you for your work on this. We really appreciate it!

**Review by vepatel — APPROVED** [review]

**Comment by haywoodsh** [comment]
Thanks for your contribution @hafe!

**Pull request merged**
