### PR TITLE
Added configmap option to turn on proxy protocol and set_real_ip_from

### PR DESCRIPTION
**Pull request by thetechnick**
As discussed in #73

### CODE REVIEW

**Comment by pleshakov** [comment]
@thetechnick thx for another pull request!

Couple of suggestions:

1. The reason I suggested to use the `proxy-protocol` and `proxy-protocol-from` keys is that setting those keys results in setting several (`set_real_ip_from`, `real_ip_header`) NGINX directives and changing the `listen` directive. So that using fewer keys makes configuration a little easier.
If you'd like to have the `set-real-ip-from` key, I suggest to also add  the `real-ip-header` key. This way to enable proxy protocol the user has to set `proxy-protocol: "True"` and if the users wants to see the IP from the proxy protocol in the logs as well as in the headers to backends, he will need to set the `set-real-ip-from` and `real_ip_header` keys.
(Also, it makes sense to add the 	real-ip-recursive key as it is the last remaining directive of the real ip module http://nginx.org/en/docs/http/ngx_http_realip_module.html)

2. If the the `real_ip_header` is set to `proxy_protocol` and the `set_real_ip_from` is set to the correct address, the `$remote_addr` variable will contain the IP obtained via proxy protocol. Thus, it's not necessary  to use `$proxy_protocol_addr` variable in the `proxy_set_header` directives.

3. In the `TestGetMapKeyAsStringSlice` test, I suggest to have:
```go
expected := []string{"1.String","2.String","3.String"}
fmt.Println(expected)
if !reflect.DeepEqual(expected, slice) {
	t.Errorf("Unexpected return value:\nGot: %v\nExpected: %v", slice, expected)
}
```

4. I created a pool request https://github.com/nginxinc/kubernetes-ingress/pull/82 that changes GetMapKeyAs* functions and fixes a few bugs in parsing when values were set to the config regardless of the presence of keys or annotations.

**Comment by thetechnick** [comment]
@pleshakov 
Sounds good

**Comment by pleshakov** [comment]
@thetechnick thx. Looks good! I added few comments about the unit test.

**Comment by thetechnick** [comment]
@pleshakov 
Where did you add your comments?
I have not found them, or am I too impatient :)

**Comment by pleshakov** [comment]
@thetechnick
> Where did you add your comments?
I have not found them, or am I too impatient :) 

My apologies. I forget to publish the comments

**Comment by thetechnick** [comment]
@pleshakov 
Ok the unittest was quite broken for this one :)
fixed in latest commit

**Comment by pleshakov** [comment]
@thetechnick Great! Could you squash the two commits?

**Comment by thetechnick** [comment]
@pleshakov done

**Comment by pleshakov** [comment]
@thetechnick thx!

**Pull request merged**
