### PR TITLE
Add HPA Custom Behavior

### PR DESCRIPTION
**Pull request by saedx1**
### Proposed changes

There is no issue for this pull request. It is a very basic PR.
It adds the ability to define `spec.behavior` for an `HorizontalPodAutoscaler`.
- Defines it in the `values.yaml` file; defaults to empty.
- References it in the controller hpa template.

### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Comment by vepatel** [comment]
Hi @saedx1 thanks for opening a PR, please make sure to follow  https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md#open-a-pull-request

**Comment by saedx1** [comment]
> Hi @saedx1 thanks for opening a PR, please make sure to follow https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md#open-a-pull-request

Hi @vepatel , Let me know if an issue is still needed in this case. The proposed change is trivial and does not affect current functionality, however, if you think an issue is needed for further discussion, I will open one.

**Comment by saedx1** [comment]
> @saedx1 Yes would really appreciate, as it helps us prioritise reviews and tests against community PRs :) Also please make sure to:
> 
> > Fork the repo, create a branch, submit a PR when your changes are tested and ready for review

Done

**Comment by haywoodsh** [comment]
Thanks @saedx1! I deployed the helm chart and the HPA resource was configured correctly.
Could you please also update the readme and the docs to include the helm parameter you added?
https://github.com/nginxinc/kubernetes-ingress/blob/v3.3.0/deployments/helm-chart/README.md 
https://github.com/nginxinc/kubernetes-ingress/blob/v3.3.0/docs/content/installation/installation-with-helm.md

**Comment by lucacome** [comment]
The right file to update is https://github.com/nginxinc/kubernetes-ingress/blob/main/charts/nginx-ingress/README.md. It's copied automatically to the docs on release.

**Comment by saedx1** [comment]
@haywoodsh @lucacome  Done :D

**Review by lucacome — APPROVED** [review]

**Review by haywoodsh — APPROVED** [review]

**Comment by saedx1** [comment]
@haywoodsh  @lucacome  Can we merge this?

**Comment by coolbry95** [comment]
This should have a doc change.

**Comment by saedx1** [comment]
> This should have a doc change.

It does. See comments above also

**Comment by coolbry95** [comment]
> > This should have a doc change.
> 
> It does. See comments above also

That will only add it to the readme.

This is when I originally implemented the HPA which adds docs so that they will show up in the website.
https://github.com/nginxinc/kubernetes-ingress/pull/3276

**Comment by jjngx** [comment]
@saedx1 could you please update your branch to get it read to be merged?

**Comment by jasonwilliams14** [comment]
@saedx1 Thanks for the contribution and great work! We appreciate it very much!!

**Pull request merged**
