### PR TITLE
Add gotype comments in templates to map types between go template and go files

### LINKED ISSUE #4159: Link structs between go templates and go files for easier development #4155
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I can't find remember which go struct the nginx config go template is referring to, and have to go through the go files to find the correct one.

**Describe the solution you'd like**
For IntelliJ and supported IDEs, add `{{- /*gotype: package/import/path.type_name*/ -}}` in the NGINX config template header.

**Describe alternatives you've considered**
This is the only solution I found.

**Additional context**
This is the screenshot of how it would look like in a supported IDE.
image 
Browse the definition on `pkg.dev.go`
image
Autocomplete:
image

### PR DESCRIPTION
**Pull request by haywoodsh**
### Proposed changes

Add gotype comments to specify mapping of types between Go templates (.tmpl) and go files (.go) 
closes #4159 

### Testing
This is the screenshot of how it would look like in IntelliJ or GoLand. For example, `$u.Servers` links to the field `Servers` in `[]StreamUpstreamServer` struct
image
Browse the definition on `pkg.dev.go`. Note the that information on the website is stuck on v1.12.5 until https://github.com/nginxinc/kubernetes-ingress/issues/3770 is resolved.
image
Autocomplete:
image

However, I tested this syntax for IntelliJ and GoLand only. For other unsupported IDE the comments still provide developer hints on which go file to look for the go struct definition.
### Checklist

Before creating a PR, run through this checklist and mark each as complete.

- [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [ ] I have rebased my branch onto main
- [ ] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Comment by lucacome** [comment]
Does this work only in IntelliJ?

**Comment by jjngx** [comment]
A good idea 👍🏻 VSCode supports this feature too. Apart from IDE support, the comments help to understand the code.

**Comment by shaun-nx** [comment]
> Does this work only in IntelliJ?

You will only get the popups linking to the go structs in IntelliJ.
That being said, it would still help in general to have this in our templates.

For example, for the VirtualServer templates, you would have this block
```
{{- /*gotype: github.com/nginxinc/kubernetes-ingress/internal/configs/version2.VirtualServerConfig*/ -}}
```

This makes it very obvious which file in the project holds the go structs related to this template.

**Review by jjngx — APPROVED** [review]
👍🏻

**Review by vepatel — APPROVED** [review]

**Comment by lucacome** [comment]
> A good idea 👍🏻 VSCode supports this feature too. Apart from IDE support, the comments help to understand the code.

@jjngx how do you use it in VS Code?

**Comment by jjngx** [comment]
> > A good idea 👍🏻 VSCode supports this feature too. Apart from IDE support, the comments help to understand the code.
> 
> @jjngx how do you use it in VS Code?

I don't use it.

**Pull request merged**
