### PR TITLE
Update VirtualServer to ignore CRL for EgressMTLS

### PR DESCRIPTION
**Pull request by shaun-nx**
### Proposed changes
This change updates the logic which applies policies to VirtualServer to ignore CRL for EgressMTLS.
Resolves https://github.com/nginxinc/kubernetes-ingress/issues/3732

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Review by lucacome — CHANGES_REQUESTED** [review]
I don't think we want to ignore the CRL. We should use the right directive for it `proxy_ssl_crl`.

**Comment by brianehlert** [comment]
> I don't think we want to ignore the CRL. We should use the right directive for it `proxy_ssl_crl`.

That would be the right thing to do.

**Comment by shaun-nx** [comment]
@brianehlert @lucacome 
The aim of this PR isn't to support using CRLs with EgressMTLs. This only addresses the issue posted in https://github.com/nginxinc/kubernetes-ingress/issues/3732

We only added support for CRLs with IngressMTLs but not EgressMTLs.
The PR for IngressMTLs update is here for reference: https://github.com/nginxinc/kubernetes-ingress/pull/3632

**Comment by brianehlert** [comment]
To close this conversation, we will be adding proper EgressMTLS support for CRL to match IngressMTLS behavior.
That is not work contained in this PR.

**Review by vepatel — APPROVED** [review]

**Review by jjngx — APPROVED** [review]

**Review by ciarams87 — APPROVED** [review]

**Pull request merged**
