### PR TITLE
Refactor Helm Chart location

### PR DESCRIPTION
**Pull request by lucacome**
### Proposed changes

First part of #4287

Moves the helm chart to a more standard location `charts/nginx-ingress`.

### CODE REVIEW

**Review by ADubhlaoich — APPROVED** [review]
LGTM, little to add from a docs perspective.

**Review by jjngx — DISMISSED** [review]

**Review by jasonwilliams14 — APPROVED** [review]
Looks good. Changing of folder location.
@lucacome do we need to update anything in our install docs?

**Comment by lucacome** [comment]
@jasonwilliams14 there shouldn't be anything else in the docs referencing the chart location.

**Comment by haywoodsh** [comment]
Hi @lucacome, can you rebase the branch from main and resolve the conflicts please?

**Comment by lucacome** [comment]
done @haywoodsh

**Review by jjngx — APPROVED** [review]

**Review by shaun-nx — APPROVED** [review]

**Pull request merged**
