### PR TITLE
Release 2.0.0

### PR DESCRIPTION
**Pull request by ciarams87**
### Proposed changes
Merge release 2.0.0 in the repo.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [ ] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/master/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have checked that all unit tests pass after adding my changes
- [ ] I have updated necessary documentation
- [ ] I have rebased my branch onto master
- [ ] I will ensure my PR is targeting the master branch and pulling from my branch from my own fork

### CODE REVIEW

**Review by lucacome — COMMENTED** [review]
Seems like it's pulling in commits that are already in master? 🤔

**Comment by lucacome** [comment]
Also with a squash and merge, the tag will not end up in master

**Comment by pleshakov** [comment]
do we need to merge this branch? how are we going to maintain docs (what branch) for docs.nginx.com? we can't do it in the master, since the master will include features for the next IC release.

**Comment by ciarams87** [comment]
> Also with a squash and merge, the tag will not end up in master

There was merge conflicts so I couldn't do a clean merge with the tag (as the tag is immutable, I couldn't change it). I'll try a different tactic, but we still may not get the tag in master.

**Comment by ciarams87** [comment]
> do we need to merge this branch? how are we going to maintain docs (what branch) for docs.nginx.com? we can't do it in the master, since the master will include features for the next IC release.

We need to merge all the docs changes to master, yes. The docs production branch is (and will continue to be) release-2.0.

**Pull request closed without merging**
