### PR TITLE
docs: Correct Security link to Installation page

### PR DESCRIPTION
**Pull request by sigv**
### Proposed changes

The resource being referenced is actually available at https://docs.nginx.com/nginx-ingress-controller/installation/installation-with-helm/#configuration but the current link does not include `installation/` subdirectory. This commit remedies that so that people can look up the reference page quicker.

### Checklist
Before creating a PR, run through this checklist and mark each as complete.

- [x] I have read the [CONTRIBUTING](https://github.com/nginxinc/kubernetes-ingress/blob/main/CONTRIBUTING.md) doc
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have checked that all unit tests pass after adding my changes
- [x] I have updated necessary documentation
- [x] I have rebased my branch onto main
- [x] I will ensure my PR is targeting the main branch and pulling from my branch from my own fork

### CODE REVIEW

**Comment by sigv** [comment]
Of note: As the change was introduced in [`d9f4a7a`](https://github.com/nginxinc/kubernetes-ingress/commit/d9f4a7ac975da0e55b97aa697ec1ea3c4d14f7d2), it is on [`release-3.1`](https://github.com/nginxinc/kubernetes-ingress/tree/release-3.1) branch and accordingly [the live documentation](https://docs.nginx.com/nginx-ingress-controller/configuration/security/#configure-root-filesystem-as-read-only).

**Comment by shaun-nx** [comment]
Nice catch @sigv !
I've opened a new PR with this change to point to our `release-3.1` branch. This will get published once the change is merged to that branch https://github.com/nginxinc/kubernetes-ingress/pull/3702

**Comment by shaun-nx** [comment]
> If this gets published to `release-3.1`, I presume `release-3.1` will get merged into `main` later -- do I close this PR?

Yes, once we're done with all of our release tasks the `release-3.1` branch gets merged into `main` so we can close this PR for now. I also realise that it would have just been easier to update this PR to point to `nginxinc:release-3.1` instead of making a new PR 😅 sorry if that seemed a bit confusing.

**Comment by sigv** [comment]
No worries about it. Was just asking to clarify 👍🏻

**Comment by vepatel** [comment]
@sigv That change has been merged now 👍🏼

**Pull request closed without merging**
