### PR TITLE
Add support for configuring pxoxy-buffer-settings

### PR DESCRIPTION
**Pull request by df-mreidel**
A small patch to enable configuring `proxy_buffers` and `proxy_buffer_size` which is necessary especially when your backends send a lot of headers and you want to increase the default value.

### CODE REVIEW

**Comment by pleshakov** [comment]
@df-mreidel 
Thanks for the pull request!

I have few suggestions:

- Since buffering requirements can differ from an application to an application, it's better to make them configurable per Ingress resource, similar to what we have for the `proxy_read_timeout` directive.
- There are a couple of others important buffering-releated NGINX directives:
  - [http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_buffering](proxy_buffering), which turns buffering on/off.
  - [http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_max_temp_file_size](proxy_max_temp_file_size), which can disable buffering responses to temp files.

**Comment by df-mreidel** [comment]
I can make these settings configurable per resource, no problem. I'll take care of the other 2 settings as well as soon as I'm back to work. Thanks for looking over it!

**Comment by df-mreidel** [comment]
Okay, made it location-aware and added your suggestions. Already tested and working.

**Comment by pleshakov** [comment]
@df-mreidel 
Awesome! thx!

**Pull request merged**
